In [2]:
import json
import pandas as pd
from tqdm import tqdm
import pickle
import numpy as np

# 구문 분석 말뭉치
- NXDP1902103231 : 문어 200만 어절
- SXDP2002103180 : 구어 100만 어절

In [1]:
# load json file
with open('C:/big15/project_data/구문 분석 말뭉치(버전 2.0)/NXDP1902103231.json','r',encoding='utf-8-sig') as f:
    js = json.load(f)

# json -> dataframe
## document 내부에 data가 더 있음을 확인
js_data = pd.json_normalize(js)
js_data.head()

NameError: name 'json' is not defined

In [76]:
js.keys()

dict_keys(['id', 'metadata', 'document'])

In [4]:
# dataframe 구조 확인
print(type(js_data))

print('-'*70)

# keys(=head) 확인
print(js_data.keys())

<class 'pandas.core.frame.DataFrame'>
----------------------------------------------------------------------
Index(['id', 'document', 'metadata.title', 'metadata.creator',
       'metadata.distributor', 'metadata.year', 'metadata.category',
       'metadata.annotation_level', 'metadata.sampling'],
      dtype='object')

In [5]:
# json -> dataframe
## document 풀기
js_document = pd.json_normalize(js['document'])
js_document

,id,sentence,metadata.title,metadata.author,metadata.publisher,metadata.date,metadata.topic
0,NWRW1800000021.1,"[{'id': 'NWRW1800000021.1.1.1', 'form': '판교 중대...",동아일보 2009년 기사,손효림 기자 aryssong@donga.com,동아일보사,20090103,NA
1,NWRW1800000021.3,"[{'id': 'NWRW1800000021.3.1.1', 'form': '“빅3 흔...",동아일보 2009년 기사,이헌진 기자 mungchii@donga.com,동아일보사,20090106,NA
2,NWRW1800000021.4,"[{'id': 'NWRW1800000021.4.1.1', 'form': '속끓는 평...",동아일보 2009년 기사,평택=이성호 기자 starsky@donga.com 의정부=이동영 기자 argus@d...,동아일보사,20090106,NA
3,NWRW1800000021.5,"[{'id': 'NWRW1800000021.5.1.1', 'form': '[대구/경...",동아일보 2009년 기사,정용균 기자 cavatina@donga.com,동아일보사,20090107,NA
4,NWRW1800000021.6,"[{'id': 'NWRW1800000021.6.1.1', 'form': '與, 쟁점...",동아일보 2009년 기사,조수진 기자 jin0619@donga.com,동아일보사,20090107,NA
...,...,...,...,...,...,...,...
7260,NWRW1800000056.389,"[{'id': 'NWRW1800000056.389.1.1', 'form': '[단독...",한겨레 2017년 기사,서영지 기자 yj@hani.co.kr,한겨레,20171123,NA
7261,NWRW1800000056.390,"[{'id': 'NWRW1800000056.390.1.1', 'form': '‘실리...",한겨레 2017년 기사,송경화 김남일 기자 freehwa@hani.co.kr,한겨레,20171206,NA
7262,NWRW1800000056.391,"[{'id': 'NWRW1800000056.391.1.1', 'form': '민주당...",한겨레 2017년 기사,"김태규, 성연철 기자 dokbul@hani.co.kr",한겨레,20171212,NA
7263,NWRW1800000056.392,"[{'id': 'NWRW1800000056.392.1.1', 'form': '유엔 ...",한겨레 2017년 기사,"정인환, 김지은 기자 inhwan@hani.co.kr",한겨레,20171215,NA
7264,NWRW1800000056.393,"[{'id': 'NWRW1800000056.393.1.1', 'form': '말바꾼...",한겨레 2017년 기사,강희철 기자 hckang@hani.co.kr,한겨레,20171228,NA

In [30]:
# sentence 내부 구조 확인
## id, form, word, DP
print(type(js_document['sentence'][0]))
js_document['sentence'][0]

<class 'list'>

[{'id': 'NWRW1800000021.1.1.1',
  'form': '판교 중대형 분양가 3.3㎡당 1500만원대…',
  'word': [{'id': 1, 'form': '판교', 'begin': 0, 'end': 2},
   {'id': 2, 'form': '중대형', 'begin': 3, 'end': 6},
   {'id': 3, 'form': '분양가', 'begin': 7, 'end': 10},
   {'id': 4, 'form': '3.3㎡당', 'begin': 11, 'end': 16},
   {'id': 5, 'form': '1500만원대…', 'begin': 17, 'end': 25}],
  'DP': [{'word_id': 1,
    'word_form': '판교',
    'head': 2,
    'label': 'NP',
    'dependent': []},
   {'word_id': 2,
    'word_form': '중대형',
    'head': 3,
    'label': 'NP',
    'dependent': [1]},
   {'word_id': 3,
    'word_form': '분양가',
    'head': 5,
    'label': 'NP_SBJ',
    'dependent': [2]},
   {'word_id': 4,
    'word_form': '3.3㎡당',
    'head': 5,
    'label': 'NP',
    'dependent': []},
   {'word_id': 5,
    'word_form': '1500만원대…',
    'head': -1,
    'label': 'NP',
    'dependent': [3, 4]}]},
 {'id': 'NWRW1800000021.1.1.2',
  'form': '2006년 보다 200만원 하락',
  'word': [{'id': 1, 'form': '2006년', 'begin': 0, 'end': 5},
   {'id': 2, 'form': '보다', 'begin': 6, 'end': 8},
   {'id': 3, 'form': '200만원', 'begin': 9, 'end': 14},
   {'id': 4, 'form': '하락', 'begin': 15, 'end': 17}],
  'DP': [{'word_id': 1,
    'word_form': '2006년',
    'head': 2,
    'label': 'NP',
    'dependent': []},
   {'word_id': 2,
    'word_form': '보다',
    'head': 4,
    'label': 'AP',
    'dependent': [1]},
   {'word_id': 3,
    'word_form': '200만원',
    'head': 4,
    'label': 'NP_SBJ',
    'dependent': []},
   {'word_id': 4,
    'word_form': '하락',
    'head': -1,
    'label': 'NP',
    'dependent': [2, 3]}]},
 {'id': 'NWRW1800000021.1.2.1',
  'form': '경기 성남시 판교신도시에서 이달 분양하는 중대형 아파트의 3.3m²당 분양가가 2006년보다 200만 원 정도 싼 1500만 원 후반대로 결정될 것으로 보인다.',
  'word': [{'id': 1, 'form': '경기', 'begin': 0, 'end': 2},
   {'id': 2, 'form': '성남시', 'begin': 3, 'end': 6},
   {'id': 3, 'form': '판교신도시에서', 'begin': 7, 'end': 14},
   {'id': 4, 'form': '이달', 'begin': 15, 'end': 17},
   {'id': 5, 'form': '분양하는', 'begin': 18, 'end': 22},
   {'id': 6, 'form': '중대형', 'begin': 23, 'end': 26},
   {'id': 7, 'form': '아파트의', 'begin': 27, 'end': 31},
   {'id': 8, 'form': '3.3m²당', 'begin': 32, 'end': 38},
   {'id': 9, 'form': '분양가가', 'begin': 39, 'end': 43},
   {'id': 10, 'form': '2006년보다', 'begin': 44, 'end': 51},
   {'id': 11, 'form': '200만', 'begin': 52, 'end': 56},
   {'id': 12, 'form': '원', 'begin': 57, 'end': 58},
   {'id': 13, 'form': '정도', 'begin': 59, 'end': 61},
   {'id': 14, 'form': '싼', 'begin': 62, 'end': 63},
   {'id': 15, 'form': '1500만', 'begin': 64, 'end': 69},
   {'id': 16, 'form': '원', 'begin': 70, 'end': 71},
   {'id': 17, 'form': '후반대로', 'begin': 72, 'end': 76},
   {'id': 18, 'form': '결정될', 'begin': 77, 'end': 80},
   {'id': 19, 'form': '것으로', 'begin': 81, 'end': 84},
   {'id': 20, 'form': '보인다.', 'begin': 85, 'end': 89}],
  'DP': [{'word_id': 1,
    'word_form': '경기',
    'head': 2,
    'label': 'NP',
    'dependent': []},
   {'word_id': 2,
    'word_form': '성남시',
    'head': 3,
    'label': 'NP',
    'dependent': [1]},
   {'word_id': 3,
    'word_form': '판교신도시에서',
    'head': 5,
    'label': 'NP_AJT',
    'dependent': [2]},
   {'word_id': 4,
    'word_form': '이달',
    'head': 5,
    'label': 'NP_AJT',
    'dependent': []},
   {'word_id': 5,
    'word_form': '분양하는',
    'head': 7,
    'label': 'VP_MOD',
    'dependent': [3, 4]},
   {'word_id': 6,
    'word_form': '중대형',
    'head': 7,
    'label': 'NP',
    'dependent': []},
   {'word_id': 7,
    'word_form': '아파트의',
    'head': 9,
    'label': 'NP_MOD',
    'dependent': [5, 6]},
   {'word_id': 8,
    'word_form': '3.3m²당',
    'head': 9,
    'label': 'NP',
    'dependent': []},
   {'word_id': 9,
    'word_form': '분양가가',
    'head': 18,
    'label': 'NP_SBJ',
    'dependent': [7, 8]},
   {'word_id': 10,
    'word_form': '2006년보다',
    'head': 14,
    'label': 'NP_AJT',
    'dependent': []},
   {'word_id': 11,
    'word_form': '200만',
    'head': 12,
    'label': 'NP',
    'dependent': []},
   {'word_id': 12,
    'word_form': '원',
    'head': 13,
    'label': 'NP',
    'dependent': [11]},
   {'word_id': 13,
    'word_form': '정도',
    'head': 14,
    'label': 'NP_AJT',
    'dependent': [12]},
   {'word_id': 14,
    'word_form': '싼',
    'head': 16,
    'label': 'VP_MOD',
    'dependent': [10, 13]},
   {'word_id': 15,
    'word_form': '1500만',
    'head': 16,
    'label': 'NP',
    'dependent': []},
   {'word_id': 16,
    'word_form': '원',
    'head': 17,
    'label': 'NP',
    'dependent': [14, 15]},
   {'word_id': 17,
    'word_form': '후반대로',
    'head': 18,
    'label': 'NP_AJT',
    'dependent': [16]},
   {'word_id': 18,
    'word_form': '결정될',
    'head': 19,
    'label': 'VP_MOD',
    'dependent': [9, 17]},
   {'word_id': 19,
    'word_form': '것으로',
    'head': 20,
    'label': 'NP_AJT',
    'dependent': [18]},
   {'word_id': 20,
    'word_form': '보인다.',
    'head': -1,
    'label': 'VP',
    'dependent': [19]}]},
 {'id': 'NWRW1800000021.1.3.1',
  'form': '2일 국토해양부와 대우건설 등에 따르면 판교신도시 A20-2블록에서 중대형 아파트 948채의 분양승인 신청을 받은 성남시는 5일 분양가심사위원회 회의를 열어 분양가를 결정할 예정이다.',
  'word': [{'id': 1, 'form': '2일', 'begin': 0, 'end': 2},
   {'id': 2, 'form': '국토해양부와', 'begin': 3, 'end': 9},
   {'id': 3, 'form': '대우건설', 'begin': 10, 'end': 14},
   {'id': 4, 'form': '등에', 'begin': 15, 'end': 17},
   {'id': 5, 'form': '따르면', 'begin': 18, 'end': 21},
   {'id': 6, 'form': '판교신도시', 'begin': 22, 'end': 27},
   {'id': 7, 'form': 'A20-2블록에서', 'begin': 28, 'end': 37},
   {'id': 8, 'form': '중대형', 'begin': 38, 'end': 41},
   {'id': 9, 'form': '아파트', 'begin': 42, 'end': 45},
   {'id': 10, 'form': '948채의', 'begin': 46, 'end': 51},
   {'id': 11, 'form': '분양승인', 'begin': 52, 'end': 56},
   {'id': 12, 'form': '신청을', 'begin': 57, 'end': 60},
   {'id': 13, 'form': '받은', 'begin': 61, 'end': 63},
   {'id': 14, 'form': '성남시는', 'begin': 64, 'end': 68},
   {'id': 15, 'form': '5일', 'begin': 69, 'end': 71},
   {'id': 16, 'form': '분양가심사위원회', 'begin': 72, 'end': 80},
   {'id': 17, 'form': '회의를', 'begin': 81, 'end': 84},
   {'id': 18, 'form': '열어', 'begin': 85, 'end': 87},
   {'id': 19, 'form': '분양가를', 'begin': 88, 'end': 92},
   {'id': 20, 'form': '결정할', 'begin': 93, 'end': 96},
   {'id': 21, 'form': '예정이다.', 'begin': 97, 'end': 102}],
  'DP': [{'word_id': 1,
    'word_form': '2일',
    'head': 5,
    'label': 'NP_AJT',
    'dependent': []},
   {'word_id': 2,
    'word_form': '국토해양부와',
    'head': 3,
    'label': 'NP_CNJ',
    'dependent': []},
   {'word_id': 3,
    'word_form': '대우건설',
    'head': 4,
    'label': 'NP',
    'dependent': [2]},
   {'word_id': 4,
    'word_form': '등에',
    'head': 5,
    'label': 'NP_AJT',
    'dependent': [3]},
   {'word_id': 5,
    'word_form': '따르면',
    'head': 18,
    'label': 'VP',
    'dependent': [1, 4]},
   {'word_id': 6,
    'word_form': '판교신도시',
    'head': 7,
    'label': 'NP',
    'dependent': []},
   {'word_id': 7,
    'word_form': 'A20-2블록에서',
    'head': 13,
    'label': 'NP_AJT',
    'dependent': [6]},
   {'word_id': 8,
    'word_form': '중대형',
    'head': 9,
    'label': 'NP',
    'dependent': []},
   {'word_id': 9,
    'word_form': '아파트',
    'head': 10,
    'label': 'NP',
    'dependent': [8]},
   {'word_id': 10,
    'word_form': '948채의',
    'head': 11,
    'label': 'NP_MOD',
    'dependent': [9]},
   {'word_id': 11,
    'word_form': '분양승인',
    'head': 12,
    'label': 'NP',
    'dependent': [10]},
   {'word_id': 12,
    'word_form': '신청을',
    'head': 13,
    'label': 'NP_OBJ',
    'dependent': [11]},
   {'word_id': 13,
    'word_form': '받은',
    'head': 14,
    'label': 'VP_MOD',
    'dependent': [7, 12]},
   {'word_id': 14,
    'word_form': '성남시는',
    'head': 18,
    'label': 'NP_SBJ',
    'dependent': [13]},
   {'word_id': 15,
    'word_form': '5일',
    'head': 18,
    'label': 'NP_AJT',
    'dependent': []},
   {'word_id': 16,
    'word_form': '분양가심사위원회',
    'head': 17,
    'label': 'NP',
    'dependent': []},
   {'word_id': 17,
    'word_form': '회의를',
    'head': 18,
    'label': 'NP_OBJ',
    'dependent': [16]},
   {'word_id': 18,
    'word_form': '열어',
    'head': 20,
    'label': 'VP',
    'dependent': [5, 14, 15, 17]},
   {'word_id': 19,
    'word_form': '분양가를',
    'head': 20,
    'label': 'NP_OBJ',
    'dependent': []},
   {'word_id': 20,
    'word_form': '결정할',
    'head': 21,
    'label': 'VP_MOD',
    'dependent': [18, 19]},
   {'word_id': 21,
    'word_form': '예정이다.',
    'head': -1,
    'label': 'VNP',
    'dependent': [20]}]},
 {'id': 'NWRW1800000021.1.4.1',
  'form': '대우건설 등은 3.3m²당 분양가를 평균 1601만 원으로 신청했지만 부동산업계에서는 통상 분양가가 신청가보다 낮은 금액으로 승인된다는 점을 고려할 때 실제 분양가는 1600만 원 밑으로 내려갈 것으로 보고 있다.',
  'word': [{'id': 1, 'form': '대우건설', 'begin': 0, 'end': 4},
   {'id': 2, 'form': '등은', 'begin': 5, 'end': 7},
   {'id': 3, 'form': '3.3m²당', 'begin': 8, 'end': 14},
   {'id': 4, 'form': '분양가를', 'begin': 15, 'end': 19},
   {'id': 5, 'form': '평균', 'begin': 20, 'end': 22},
   {'id': 6, 'form': '1601만', 'begin': 23, 'end': 28},
   {'id': 7, 'form': '원으로', 'begin': 29, 'end': 32},
   {'id': 8, 'form': '신청했지만', 'begin': 33, 'end': 38},
   {'id': 9, 'form': '부동산업계에서는', 'begin': 39, 'end': 47},
   {'id': 10, 'form': '통상', 'begin': 48, 'end': 50},
   {'id': 11, 'form': '분양가가', 'begin': 51, 'end': 55},
   {'id': 12, 'form': '신청가보다', 'begin': 56, 'end': 61},
   {'id': 13, 'form': '낮은', 'begin': 62, 'end': 64},
   {'id': 14, 'form': '금액으로', 'begin': 65, 'end': 69},
   {'id': 15, 'form': '승인된다는', 'begin': 70, 'end': 75},
   {'id': 16, 'form': '점을', 'begin': 76, 'end': 78},
   {'id': 17, 'form': '고려할', 'begin': 79, 'end': 82},
   {'id': 18, 'form': '때', 'begin': 83, 'end': 84},
   {'id': 19, 'form': '실제', 'begin': 85, 'end': 87},
   {'id': 20, 'form': '분양가는', 'begin': 88, 'end': 92},
   {'id': 21, 'form': '1600만', 'begin': 93, 'end': 98},
   {'id': 22, 'form': '원', 'begin': 99, 'end': 100},
   {'id': 23, 'form': '밑으로', 'begin': 101, 'end': 104},
   {'id': 24, 'form': '내려갈', 'begin': 105, 'end': 108},
   {'id': 25, 'form': '것으로', 'begin': 109, 'end': 112},
   {'id': 26, 'form': '보고', 'begin': 113, 'end': 115},
   {'id': 27, 'form': '있다.', 'begin': 116, 'end': 119}],
  'DP': [{'word_id': 1,
    'word_form': '대우건설',
    'head': 2,
    'label': 'NP',
    'dependent': []},
   {'word_id': 2,
    'word_form': '등은',
    'head': 8,
    'label': 'NP_SBJ',
    'dependent': [1]},
   {'word_id': 3,
    'word_form': '3.3m²당',
    'head': 4,
    'label': 'NP',
    'dependent': []},
   {'word_id': 4,
    'word_form': '분양가를',
    'head': 8,
    'label': 'NP_OBJ',
    'dependent': [3]},
   {'word_id': 5,
    'word_form': '평균',
    'head': 7,
    'label': 'NP',
    'dependent': []},
   {'word_id': 6,
    'word_form': '1601만',
    'head': 7,
    'label': 'NP',
    'dependent': []},
   {'word_id': 7,
    'word_form': '원으로',
    'head': 8,
    'label': 'NP_AJT',
    'dependent': [5, 6]},
   {'word_id': 8,
    'word_form': '신청했지만',
    'head': 15,
    'label': 'VP',
    'dependent': [2, 4, 7]},
   {'word_id': 9,
    'word_form': '부동산업계에서는',
    'head': 15,
    'label': 'NP_AJT',
    'dependent': []},
   {'word_id': 10,
    'word_form': '통상',
    'head': 11,
    'label': 'NP',
    'dependent': []},
   {'word_id': 11,
    'word_form': '분양가가',
    'head': 15,
    'label': 'NP_SBJ',
    'dependent': [10]},
   {'word_id': 12,
    'word_form': '신청가보다',
    'head': 13,
    'label': 'NP_AJT',
    'dependent': []},
   {'word_id': 13,
    'word_form': '낮은',
    'head': 14,
    'label': 'VP_MOD',
    'dependent': [12]},
   {'word_id': 14,
    'word_form': '금액으로',
    'head': 15,
    'label': 'NP_AJT',
    'dependent': [13]},
   {'word_id': 15,
    'word_form': '승인된다는',
    'head': 16,
    'label': 'VP_MOD',
    'dependent': [8, 9, 11, 14]},
   {'word_id': 16,
    'word_form': '점을',
    'head': 17,
    'label': 'NP_OBJ',
    'dependent': [15]},
   {'word_id': 17,
    'word_form': '고려할',
    'head': 18,
    'label': 'VP_MOD',
    'dependent': [16]},
   {'word_id': 18,
    'word_form': '때',
    'head': 24,
    'label': 'NP_AJT',
    'dependent': [17]},
   {'word_id': 19,
    'word_form': '실제',
    'head': 20,
    'label': 'NP',
    'dependent': []},
   {'word_id': 20,
    'word_form': '분양가는',
    'head': 24,
    'label': 'NP_SBJ',
    'dependent': [19]},
   {'word_id': 21,
    'word_form': '1600만',
    'head': 22,
    'label': 'NP',
    'dependent': []},
   {'word_id': 22,
    'word_form': '원',
    'head': 23,
    'label': 'NP',
    'dependent': [21]},
   {'word_id': 23,
    'word_form': '밑으로',
    'head': 24,
    'label': 'NP_AJT',
    'dependent': [22]},
   {'word_id': 24,
    'word_form': '내려갈',
    'head': 25,
    'label': 'VP_MOD',
    'dependent': [18, 20, 23]},
   {'word_id': 25,
    'word_form': '것으로',
    'head': 26,
    'label': 'NP_AJT',
    'dependent': [24]},
   {'word_id': 26,
    'word_form': '보고',
    'head': 27,
    'label': 'VP',
    'dependent': [25]},
   {'word_id': 27,
    'word_form': '있다.',
    'head': -1,
    'label': 'VP',
    'dependent': [26]}]},
 {'id': 'NWRW1800000021.1.5.1',
  'form': '이 아파트는 대우건설과 서해종합건설이 공동 시공하며 123∼337m² 규모다.',
  'word': [{'id': 1, 'form': '이', 'begin': 0, 'end': 1},
   {'id': 2, 'form': '아파트는', 'begin': 2, 'end': 6},
   {'id': 3, 'form': '대우건설과', 'begin': 7, 'end': 12},
   {'id': 4, 'form': '서해종합건설이', 'begin': 13, 'end': 20},
   {'id': 5, 'form': '공동', 'begin': 21, 'end': 23},
   {'id': 6, 'form': '시공하며', 'begin': 24, 'end': 28},
   {'id': 7, 'form': '123∼337m²', 'begin': 29, 'end': 38},
   {'id': 8, 'form': '규모다.', 'begin': 39, 'end': 43}],
  'DP': [{'word_id': 1,
    'word_form': '이',
    'head': 2,
    'label': 'DP',
    'dependent': []},
   {'word_id': 2,
    'word_form': '아파트는',
    'head': 6,
    'label': 'NP_OBJ',
    'dependent': [1]},
   {'word_id': 3,
    'word_form': '대우건설과',
    'head': 4,
    'label': 'NP_CNJ',
    'dependent': []},
   {'word_id': 4,
    'word_form': '서해종합건설이',
    'head': 6,
    'label': 'NP_SBJ',
    'dependent': [3]},
   {'word_id': 5,
    'word_form': '공동',
    'head': 6,
    'label': 'NP',
    'dependent': []},
   {'word_id': 6,
    'word_form': '시공하며',
    'head': 8,
    'label': 'VP',
    'dependent': [2, 4, 5]},
   {'word_id': 7,
    'word_form': '123∼337m²',
    'head': 8,
    'label': 'NP',
    'dependent': []},
   {'word_id': 8,
    'word_form': '규모다.',
    'head': -1,
    'label': 'VNP',
    'dependent': [6, 7]}]},
 {'id': 'NWRW1800000021.1.5.2',
  'form': '민간건설사가 분양하는 판교신도시의 마지막 중대형 물량으로 채권입찰제는 적용하지 않는다.',
  'word': [{'id': 1, 'form': '민간건설사가', 'begin': 0, 'end': 6},
   {'id': 2, 'form': '분양하는', 'begin': 7, 'end': 11},
   {'id': 3, 'form': '판교신도시의', 'begin': 12, 'end': 18},
   {'id': 4, 'form': '마지막', 'begin': 19, 'end': 22},
   {'id': 5, 'form': '중대형', 'begin': 23, 'end': 26},
   {'id': 6, 'form': '물량으로', 'begin': 27, 'end': 31},
   {'id': 7, 'form': '채권입찰제는', 'begin': 32, 'end': 38},
   {'id': 8, 'form': '적용하지', 'begin': 39, 'end': 43},
   {'id': 9, 'form': '않는다.', 'begin': 44, 'end': 48}],
  'DP': [{'word_id': 1,
    'word_form': '민간건설사가',
    'head': 2,
    'label': 'NP_SBJ',
    'dependent': []},
   {'word_id': 2,
    'word_form': '분양하는',
    'head': 3,
    'label': 'VP_MOD',
    'dependent': [1]},
   {'word_id': 3,
    'word_form': '판교신도시의',
    'head': 6,
    'label': 'NP_MOD',
    'dependent': [2]},
   {'word_id': 4,
    'word_form': '마지막',
    'head': 5,
    'label': 'NP',
    'dependent': []},
   {'word_id': 5,
    'word_form': '중대형',
    'head': 6,
    'label': 'NP',
    'dependent': [4]},
   {'word_id': 6,
    'word_form': '물량으로',
    'head': 8,
    'label': 'NP_AJT',
    'dependent': [3, 5]},
   {'word_id': 7,
    'word_form': '채권입찰제는',
    'head': 8,
    'label': 'NP_OBJ',
    'dependent': []},
   {'word_id': 8,
    'word_form': '적용하지',
    'head': 9,
    'label': 'VP',
    'dependent': [6, 7]},
   {'word_id': 9,
    'word_form': '않는다.',
    'head': -1,
    'label': 'VP',
    'dependent': [8]}]},
 {'id': 'NWRW1800000021.1.6.1',
  'form': '2006년 채권입찰제를 적용해 분양했던 판교신도시 중대형 아파트의 실제 분양가가 3.3m²당 1800여만 원이었던 것과 비교하면 이번에 분양하는 중대형 아파트는 3.3m²당 200만 원가량 싼 셈이다.',
  'word': [{'id': 1, 'form': '2006년', 'begin': 0, 'end': 5},
   {'id': 2, 'form': '채권입찰제를', 'begin': 6, 'end': 12},
   {'id': 3, 'form': '적용해', 'begin': 13, 'end': 16},
   {'id': 4, 'form': '분양했던', 'begin': 17, 'end': 21},
   {'id': 5, 'form': '판교신도시', 'begin': 22, 'end': 27},
   {'id': 6, 'form': '중대형', 'begin': 28, 'end': 31},
   {'id': 7, 'form': '아파트의', 'begin': 32, 'end': 36},
   {'id': 8, 'form': '실제', 'begin': 37, 'end': 39},
   {'id': 9, 'form': '분양가가', 'begin': 40, 'end': 44},
   {'id': 10, 'form': '3.3m²당', 'begin': 45, 'end': 51},
   {'id': 11, 'form': '1800여만', 'begin': 52, 'end': 58},
   {'id': 12, 'form': '원이었던', 'begin': 59, 'end': 63},
   {'id': 13, 'form': '것과', 'begin': 64, 'end': 66},
   {'id': 14, 'form': '비교하면', 'begin': 67, 'end': 71},
   {'id': 15, 'form': '이번에', 'begin': 72, 'end': 75},
   {'id': 16, 'form': '분양하는', 'begin': 76, 'end': 80},
   {'id': 17, 'form': '중대형', 'begin': 81, 'end': 84},
   {'id': 18, 'form': '아파트는', 'begin': 85, 'end': 89},
   {'id': 19, 'form': '3.3m²당', 'begin': 90, 'end': 96},
   {'id': 20, 'form': '200만', 'begin': 97, 'end': 101},
   {'id': 21, 'form': '원가량', 'begin': 102, 'end': 105},
   {'id': 22, 'form': '싼', 'begin': 106, 'end': 107},
   {'id': 23, 'form': '셈이다.', 'begin': 108, 'end': 112}],
  'DP': [{'word_id': 1,
    'word_form': '2006년',
    'head': 3,
    'label': 'NP_AJT',
    'dependent': []},
   {'word_id': 2,
    'word_form': '채권입찰제를',
    'head': 3,
    'label': 'NP_OBJ',
    'dependent': []},
   {'word_id': 3,
    'word_form': '적용해',
    'head': 4,
    'label': 'VP',
    'dependent': [1, 2]},
   {'word_id': 4,
    'word_form': '분양했던',
    'head': 7,
    'label': 'VP_MOD',
    'dependent': [3]},
   {'word_id': 5,
    'word_form': '판교신도시',
    'head': 7,
    'label': 'NP',
    'dependent': []},
   {'word_id': 6,
    'word_form': '중대형',
    'head': 7,
    'label': 'NP',
    'dependent': []},
   {'word_id': 7,
    'word_form': '아파트의',
    'head': 9,
    'label': 'NP_MOD',
    'dependent': [4, 5, 6]},
   {'word_id': 8,
    'word_form': '실제',
    'head': 9,
    'label': 'NP',
    'dependent': []},
   {'word_id': 9,
    'word_form': '분양가가',
    'head': 12,
    'label': 'NP_SBJ',
    'dependent': [7, 8]},
   {'word_id': 10,
    'word_form': '3.3m²당',
    'head': 12,
    'label': 'NP_AJT',
    'dependent': []},
   {'word_id': 11,
    'word_form': '1800여만',
    'head': 12,
    'label': 'NP',
    'dependent': []},
   {'word_id': 12,
    'word_form': '원이었던',
    'head': 13,
    'label': 'VNP_MOD',
    'dependent': [9, 10, 11]},
   {'word_id': 13,
    'word_form': '것과',
    'head': 14,
    'label': 'NP_AJT',
    'dependent': [12]},
   {'word_id': 14,
    'word_form': '비교하면',
    'head': 22,
    'label': 'VP',
    'dependent': [13]},
   {'word_id': 15,
    'word_form': '이번에',
    'head': 16,
    'label': 'NP_AJT',
    'dependent': []},
   {'word_id': 16,
    'word_form': '분양하는',
    'head': 18,
    'label': 'VP_MOD',
    'dependent': [15]},
   {'word_id': 17,
    'word_form': '중대형',
    'head': 18,
    'label': 'NP',
    'dependent': []},
   {'word_id': 18,
    'word_form': '아파트는',
    'head': 22,
    'label': 'NP_SBJ',
    'dependent': [16, 17]},
   {'word_id': 19,
    'word_form': '3.3m²당',
    'head': 21,
    'label': 'NP',
    'dependent': []},
   {'word_id': 20,
    'word_form': '200만',
    'head': 21,
    'label': 'NP',
    'dependent': []},
   {'word_id': 21,
    'word_form': '원가량',
    'head': 22,
    'label': 'NP_SBJ',
    'dependent': [19, 20]},
   {'word_id': 22,
    'word_form': '싼',
    'head': 23,
    'label': 'VP_MOD',
    'dependent': [14, 18, 21]},
   {'word_id': 23,
    'word_form': '셈이다.',
    'head': -1,
    'label': 'VNP',
    'dependent': [22]}]}]

In [34]:
# dataframe -> sentence 추출 -> DataFrame
## 이전 dataframe의 id를 가져올 필요가 있음
## 이전 id가 각 문장의 단어들을 구분
js_document_sentence = pd.DataFrame()
for i in tqdm(js_document.index) :
    sen_sentence = pd.json_normalize(js_document['sentence'][i])
    js_document_sentence = pd.concat([js_document_sentence, sen_sentence],ignore_index=True)
js_document_sentence

100%|██████████| 7265/7265 [00:48<00:00, 150.11it/s]

,id,form,word,DP
0,NWRW1800000021.1.1.1,판교 중대형 분양가 3.3㎡당 1500만원대…,"[{'id': 1, 'form': '판교', 'begin': 0, 'end': 2}...","[{'word_id': 1, 'word_form': '판교', 'head': 2, ..."
1,NWRW1800000021.1.1.2,2006년 보다 200만원 하락,"[{'id': 1, 'form': '2006년', 'begin': 0, 'end':...","[{'word_id': 1, 'word_form': '2006년', 'head': ..."
2,NWRW1800000021.1.2.1,경기 성남시 판교신도시에서 이달 분양하는 중대형 아파트의 3.3m²당 분양가가 20...,"[{'id': 1, 'form': '경기', 'begin': 0, 'end': 2}...","[{'word_id': 1, 'word_form': '경기', 'head': 2, ..."
3,NWRW1800000021.1.3.1,2일 국토해양부와 대우건설 등에 따르면 판교신도시 A20-2블록에서 중대형 아파트 ...,"[{'id': 1, 'form': '2일', 'begin': 0, 'end': 2}...","[{'word_id': 1, 'word_form': '2일', 'head': 5, ..."
4,NWRW1800000021.1.4.1,대우건설 등은 3.3m²당 분양가를 평균 1601만 원으로 신청했지만 부동산업계에서...,"[{'id': 1, 'form': '대우건설', 'begin': 0, 'end': ...","[{'word_id': 1, 'word_form': '대우건설', 'head': 2..."
...,...,...,...,...
150077,NWRW1800000056.393.12.1,검찰 관계자는 “설령 다스 직원 개인의 횡령이 맞다 해도 정 전 특검은 기소를 하든...,"[{'id': 1, 'form': '검찰', 'begin': 0, 'end': 2}...","[{'word_id': 1, 'word_form': '검찰', 'head': 2, ..."
150078,NWRW1800000056.393.13.1,■ “MB 관여 사실무근” 대 “증거 못 찾아” “(이명박 대통령) 당선인이 ㈜다스...,"[{'id': 1, 'form': '■', 'begin': 0, 'end': 1},...","[{'word_id': 1, 'word_form': '■', 'head': 25, ..."
150079,NWRW1800000056.393.13.2,2008년 2월21일 정 전 특검은 이런 결론을 읽은 뒤 이 전 대통령을 무혐의 처...,"[{'id': 1, 'form': '2008년', 'begin': 0, 'end':...","[{'word_id': 1, 'word_form': '2008년', 'head': ..."
150080,NWRW1800000056.393.13.3,그러나 이번에 그가 낸 보도자료에는 “수사 결과 이 전 대통령이 ㈜다스의 실질적 소...,"[{'id': 1, 'form': '그러나', 'begin': 0, 'end': 3...","[{'word_id': 1, 'word_form': '그러나', 'head': 5,..."
150081,NWRW1800000056.393.13.4,"검찰의 다른 관계자는 “당시엔 ‘사실’, ‘확인’ 이런 표현으로 이 전 대통령에게 ...","[{'id': 1, 'form': '검찰의', 'begin': 0, 'end': 3...","[{'word_id': 1, 'word_form': '검찰의', 'head': 3,..."

In [39]:
# dataframe을 pickle로 저장 : js_document_sentence
with open("C:/dev/python-dev/AI-dev/workspace/data/corpus/parsing/js_document_sentence.pickle", "wb") as file:
    pickle.dump(js_document_sentence, file)

In [41]:
# pickle을 dataframe으로 불러오기 : js_document_sentence
with open("C:/dev/python-dev/AI-dev/workspace/data/corpus/parsing/js_document_sentence.pickle", "rb" ) as file:
    js_document_sentence = pickle.load(file)
js_document_sentence

,id,form,word,DP
0,NWRW1800000021.1.1.1,판교 중대형 분양가 3.3㎡당 1500만원대…,"[{'id': 1, 'form': '판교', 'begin': 0, 'end': 2}...","[{'word_id': 1, 'word_form': '판교', 'head': 2, ..."
1,NWRW1800000021.1.1.2,2006년 보다 200만원 하락,"[{'id': 1, 'form': '2006년', 'begin': 0, 'end':...","[{'word_id': 1, 'word_form': '2006년', 'head': ..."
2,NWRW1800000021.1.2.1,경기 성남시 판교신도시에서 이달 분양하는 중대형 아파트의 3.3m²당 분양가가 20...,"[{'id': 1, 'form': '경기', 'begin': 0, 'end': 2}...","[{'word_id': 1, 'word_form': '경기', 'head': 2, ..."
3,NWRW1800000021.1.3.1,2일 국토해양부와 대우건설 등에 따르면 판교신도시 A20-2블록에서 중대형 아파트 ...,"[{'id': 1, 'form': '2일', 'begin': 0, 'end': 2}...","[{'word_id': 1, 'word_form': '2일', 'head': 5, ..."
4,NWRW1800000021.1.4.1,대우건설 등은 3.3m²당 분양가를 평균 1601만 원으로 신청했지만 부동산업계에서...,"[{'id': 1, 'form': '대우건설', 'begin': 0, 'end': ...","[{'word_id': 1, 'word_form': '대우건설', 'head': 2..."
...,...,...,...,...
150077,NWRW1800000056.393.12.1,검찰 관계자는 “설령 다스 직원 개인의 횡령이 맞다 해도 정 전 특검은 기소를 하든...,"[{'id': 1, 'form': '검찰', 'begin': 0, 'end': 2}...","[{'word_id': 1, 'word_form': '검찰', 'head': 2, ..."
150078,NWRW1800000056.393.13.1,■ “MB 관여 사실무근” 대 “증거 못 찾아” “(이명박 대통령) 당선인이 ㈜다스...,"[{'id': 1, 'form': '■', 'begin': 0, 'end': 1},...","[{'word_id': 1, 'word_form': '■', 'head': 25, ..."
150079,NWRW1800000056.393.13.2,2008년 2월21일 정 전 특검은 이런 결론을 읽은 뒤 이 전 대통령을 무혐의 처...,"[{'id': 1, 'form': '2008년', 'begin': 0, 'end':...","[{'word_id': 1, 'word_form': '2008년', 'head': ..."
150080,NWRW1800000056.393.13.3,그러나 이번에 그가 낸 보도자료에는 “수사 결과 이 전 대통령이 ㈜다스의 실질적 소...,"[{'id': 1, 'form': '그러나', 'begin': 0, 'end': 3...","[{'word_id': 1, 'word_form': '그러나', 'head': 5,..."
150081,NWRW1800000056.393.13.4,"검찰의 다른 관계자는 “당시엔 ‘사실’, ‘확인’ 이런 표현으로 이 전 대통령에게 ...","[{'id': 1, 'form': '검찰의', 'begin': 0, 'end': 3...","[{'word_id': 1, 'word_form': '검찰의', 'head': 3,..."

In [35]:
# dataframe -> DP 추출 -> DataFrame
js_document_sentence_DP = pd.DataFrame()
for i in tqdm(js_document_sentence.index) :
    sen_sentence = pd.json_normalize(js_document_sentence['DP'][i])
    js_document_sentence_DP = pd.concat([js_document_sentence_DP, sen_sentence],ignore_index=True)
js_document_sentence_DP

100%|██████████| 150082/150082 [2:23:48<00:00, 17.39it/s]

         word_id word_form  head    label         dependent
0              1        판교     2       NP                []
1              2       중대형     3       NP               [1]
2              3       분양가     5   NP_SBJ               [2]
3              4     3.3㎡당     5       NP                []
4              5  1500만원대…    -1       NP            [3, 4]
...          ...       ...   ...      ...               ...
2000208       19     소극적이고    20      VNP                []
2000209       20      유보적인    21  VNP_MOD              [19]
2000210       21       표현을    22   NP_OBJ              [20]
2000211       22     썼더라”고    23   VP_CMP  [14, 15, 18, 21]
2000212       23      짚었다.    -1       VP           [3, 22]

[2000213 rows x 5 columns]

In [62]:
# dataframe을 json으로 변환 -> form을 examples를 풀 때도 가져가기 위함
test = js_document_sentence.to_json(orient='table')
parsed = json.loads(test)
parsed.keys()

dict_keys(['schema', 'data'])

In [68]:
parsed['schema']

{'fields': [{'name': 'index', 'type': 'integer'},
  {'name': 'id', 'type': 'string'},
  {'name': 'form', 'type': 'string'},
  {'name': 'word', 'type': 'string'},
  {'name': 'DP', 'type': 'string'}],
 'primaryKey': ['index'],
 'pandas_version': '1.4.0'}

In [64]:
# js_document_sentence의 DP를 DataFrame 변환
parsing_clean = pd.json_normalize(data = parsed['data'], record_path='DP', meta=['id'], record_prefix='_')
print(parsing_clean.shape)
parsing_clean.head(10)

(2000213, 6)

   _word_id _word_form  _head  _label _dependent                    id
0         1         판교      2      NP         []  NWRW1800000021.1.1.1
1         2        중대형      3      NP        [1]  NWRW1800000021.1.1.1
2         3        분양가      5  NP_SBJ        [2]  NWRW1800000021.1.1.1
3         4      3.3㎡당      5      NP         []  NWRW1800000021.1.1.1
4         5   1500만원대…     -1      NP     [3, 4]  NWRW1800000021.1.1.1
5         1      2006년      2      NP         []  NWRW1800000021.1.1.2
6         2         보다      4      AP        [1]  NWRW1800000021.1.1.2
7         3      200만원      4  NP_SBJ         []  NWRW1800000021.1.1.2
8         4         하락     -1      NP     [2, 3]  NWRW1800000021.1.1.2
9         1         경기      2      NP         []  NWRW1800000021.1.2.1

In [65]:
# dataframe을 pickle로 저장 : parsing_clean
with open("C:/dev/python-dev/AI-dev/workspace/data/corpus/parsing/parsing_clean.pickle", "wb") as file:
    pickle.dump(parsing_clean, file)

In [66]:
# pickle을 dataframe으로 불러오기 : parsing_clean
with open("C:/dev/python-dev/AI-dev/workspace/data/corpus/parsing/parsing_clean.pickle", "rb" ) as file:
    parsing_clean = pickle.load(file)
parsing_clean

,_word_id,_word_form,_head,_label,_dependent,id
0,1,판교,2,NP,[],NWRW1800000021.1.1.1
1,2,중대형,3,NP,[1],NWRW1800000021.1.1.1
2,3,분양가,5,NP_SBJ,[2],NWRW1800000021.1.1.1
3,4,3.3㎡당,5,NP,[],NWRW1800000021.1.1.1
4,5,1500만원대…,-1,NP,"[3, 4]",NWRW1800000021.1.1.1
...,...,...,...,...,...,...
2000208,19,소극적이고,20,VNP,[],NWRW1800000056.393.13.4
2000209,20,유보적인,21,VNP_MOD,[19],NWRW1800000056.393.13.4
2000210,21,표현을,22,NP_OBJ,[20],NWRW1800000056.393.13.4
2000211,22,썼더라”고,23,VP_CMP,"[14, 15, 18, 21]",NWRW1800000056.393.13.4
2000212,23,짚었다.,-1,VP,"[3, 22]",NWRW1800000056.393.13.4